### ISSUE TITLE
[Work Graphs] Remove SYNC_FLAG from Barrier intrinsics

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/hlsl-specs#101]
**Which document does this relate to?**
https://github.com/microsoft/hlsl-specs/pull/62
https://github.com/microsoft/hlsl-specs/pull/77

**Describe the issue you see with the spec**
The sync_flags parameter has been removed from the barrier intrinsic, we need to update the DXIL and WG specs.

**Additional context**

https://microsoft.github.io/DirectX-Specs/d3d/WorkGraphs.html#barrier

**Comment by pow2clk** [comment]
Should be closed by #62
