### ISSUE TITLE
[INF-0001] Consider environment as a parameter to availability attribute

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/hlsl-specs#189]
**Which proposal does this relate to?**
[INF-0001 Availability Diagnostics](https://github.com/microsoft/hlsl-specs/blob/main/proposals/infra/INF-0001-availability-diagnostics.md)

**Describe the issue or outstanding question.**
There was some back and forth in two threads [here](https://github.com/microsoft/hlsl-specs/pull/153#discussion_r1550567652) and [here](https://github.com/microsoft/hlsl-specs/pull/153#discussion_r1547497568) about the representation of the environment component of the target triple. In LLVM we use the environment to model DirectX shader stages, which are analogues to SPIR-V execution models.

The number of permutations that we need to support here could grow over time and get large. In fact, the permutations that Apple has added already have exploded in recent years. It might be worth considering adding an `environment` parameter to the attribute to reduce future explosion of permutations.

**Comment by hekota** [comment]
So if we add `environment` parameter to the clang availability attribute then we avoid adding the many `shadermodel_*` and `vulcan_*` entries and instead specify shader stage intrinsic availability with

```
__attribute__((availability(shadermodel, introduced = 2.0, environment="pixel")))
```

instead of

```
__attribute__((availability(shadermodel_pixel, introduced = 2.0)))
```

Do I understand that correctly? Is that something that would require RFC on discourse?
