### ISSUE TITLE
[INF-0001] Write up detailed design

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/hlsl-specs#190]
**Which proposal does this relate to?**
[INF-0001 Availability Diagnostics](https://github.com/microsoft/hlsl-specs/blob/main/proposals/infra/INF-0001-availability-diagnostics.md)

**Describe the issue or outstanding question.**
The document as written mostly tries to explain the user exposed behavior in detail. The details of the implementation are yet to be described.

Some questions to help frame the design:
* What diagnostics do we emit, when and where?
* We'll probably need a call graph analysis, does Clang's existing one meet our needs?
* We'll probably need to write some form of AST-traversal to visit `CallExprs`
* Should we do any attribute propagation to simplify the analysis? (i.e. if your function calls a function with an availability annotation, should we propagate that up to the caller?)

**Comment by damyanp** [comment]
@hekota is working on this, tracked by various other issues.
