### ISSUE TITLE
[0011] Allow ext_capability and ext_extension to attach to typedef declarations.

### ISSUE THREAD

**Issue by cassiebeckley** [microsoft/hlsl-specs#191]
**Which proposal does this relate to?**
https://github.com/microsoft/hlsl-specs/blob/main/proposals/0011-inline-spirv.md

**Describe the issue or outstanding question.**
Allow `ext_capability` and `ext_extension` to attach to typedef declarations. This would allow library authors to specify to the compiler that a newly declared type needs a capability or extension, and it would be added automatically whenever the user uses the type, without needing to add `ext_capability` or `ext_extension` to the entry point function or variable declaration.

**Comment by s-perron** [comment]
Done: https://github.com/microsoft/hlsl-specs/pull/270.
