### ISSUE TITLE
[INF-0001] Should we build a general infrastructure for call graph-based diagnostics

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/hlsl-specs#199]
**Which proposal does this relate to?**
[INF-0001 Availability Diagnostics](https://github.com/microsoft/hlsl-specs/blob/main/proposals/infra/INF-0001-availability-diagnostics.md)

**Describe the issue or outstanding question.**
The diagnostics described in this proposal are one class of diagnostic we need to emit which depends on call graph analysis. There are other diagnostics that depend on call graph analysis. One example is the requirements for threadgroup size in order to use derivative operations.

Should the infrastructure built for these diagnostics be general purpose enough to handle these cases as well?

**Comment by damyanp** [comment]
This is falling out of other work we're doing and doesn't need to be tracked as its own issue.
