### ISSUE TITLE
Default linkage flag - how to transition from DXC's `-default-linkage` to Clang

### ISSUE THREAD

**Issue by hekota** [microsoft/hlsl-specs#242]
In DXC the `-default-linkage` compiler flag changes the default linkage of all functions in a translation unit. It accepts values `external` and `internal` (which is the default). This issue is to track how we should transition from the DXC flag to Clang.

Clang's has `-fvisibility` flag which determines the visibility of functions, but no flag that affects linkage.

**Comment by damyanp** [comment]
@damyanp - move this to wg-hlsl

**Comment by damyanp** [comment]
Moved to https://github.com/llvm/wg-hlsl/issues/58
