### ISSUE TITLE
Verify the behavior when static globals are referenced in both control point and constant patch function in hull shader

### ISSUE THREAD

**Issue by vcsharma** [microsoft/hlsl-specs#248]
PR microsoft/DirectXShaderCompiler#1526 introduces support for writing to globals with /Gec flag and HV <= 2016. The implementation assumes a single entry point which is true almost always except in the case of hull shader. Therefore, hull shader would need additional validation to ensure the code gen vis-a-vis writing to globals, is correct.

**Comment by damyanp** [comment]
On further reflection, this only applies to HV <= 2016 and involves _writing_ to constant buffer values, this isn't something we're going to support in modern versions of hlsl.
