### ISSUE TITLE
HLSL refract() documentation shows a parameter named '?'

### ISSUE THREAD

**Issue by cheneym2** [microsoft/hlsl-specs#354]
**Which document does this relate to?**
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-refract

**Describe the issue you see with the spec**
One of the parameters is named '?' which, being an invalid identifier, seems like an indication of a bug somewhere in the document scripting.

**Additional context**

**Comment by damyanp** [comment]
Thanks - I've reported this to the documentation team. I'm going to close this here as it is now tracked elsewhere.
