### ISSUE TITLE
[0010] Feature availability check

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/hlsl-specs#40]
**Which proposal does this relate to?**
[0010-vk-buffer-ref.md](proposals/0010-vk-buffer-ref.md)

**Describe the issue or outstanding question.**
Since this is a retroactive feature, we should document and describe a feature availability check using the clang `__has_feature` infrastructure in DXC. We haven't historically used this for features, but it is much nicer than forcing users to key off specific compiler versions and I've locally tested that it is fully functional in DXC.

**Additional context**
See [initial review discussion](https://github.com/microsoft/hlsl-specs/pull/37).

**Comment by greg-lunarg** [comment]
I propose the following syntax: _has_feature(hlsl_vk_buffer_pointer)
