### ISSUE TITLE
[0010] Define casting rules for `vk::BufferPointer<T,A>`

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/hlsl-specs#44]
**Which proposal does this relate to?**
[0010-vk-buffer-ref.md](proposals/0010-vk-buffer-ref.md)

**Describe the issue or outstanding question.**
We need to define the casting rules and casting operators for `vk::BufferPointer<T,A>` objects. Completely off the top of my head, I think it would be beneficial to have a `vk::pointer_cast<>()` casting operator and enforce the legality of casts through the operator.

Open to other suggestions and explorations.

**Additional context**
See [initial review discussion](https://github.com/microsoft/hlsl-specs/pull/37).

**Comment by s-perron** [comment]
If we use the idea for aliasing in https://github.com/microsoft/hlsl-specs/issues/42#issuecomment-1511492275. I would have no problem with adding a pointer cast.

There is not type based aliasing in spir-v, so this should not cause any subtle and dangerous interactions because of the different types.

If we go with @greg-lunarg's idea to add type based aliasing, then we will have to think carefully about this. My view would be to disallow it.

**Comment by devshgraphicsprogramming** [comment]
Can we re-use syntax we're all familiar with?
```cpp
vk::BufferPointer<uint,4> pU;
auto pF = reinterpret_cast<vk::BufferPointer<float,4>>(pU);
```

Then `pointer_cast<T,A>` could just be a templated function for brevity.

Also if `pointer_cast` or `reinterpret_cast` allowed for taking `uint64_t` as a template parameter or function argument, then we could have support for "manufacturing pointers from `uint64_t`" but without the danger of implicitly making null pointers.

**Comment by greg-lunarg** [comment]
Based on requests from @natevm et al, I propose that we support a mechanism to cast from a uint64_t.

**Comment by s-perron** [comment]
> Lets say I have a `vk::BufferPointer` that points to an uint array. Will it be possible to have a `vk::BufferPointer<uint[]>` and then use `ptr.Get()[idx]` to get the uint at index `idx`? The reason I ask the question right here is because if that is not possible, I think it is very important to be able to cast from `uint64_t` to `vk::BufferPointer<T, A>`.

You should be able to put the array in a struct, and then have a pointer to that struct.

```
struct T {
  uint[];
}

vk::BufferPointer<T, A>
```
