### ISSUE TITLE
[0011] Inline spirv for builtin inputs and output

### ISSUE THREAD

**Issue by s-perron** [microsoft/hlsl-specs#76]
**Which proposal does this relate to?**
0011 Inline spirv

**Describe the issue or outstanding question.**

Is there a better alternative for representing builtin inputs and builtin outputs?

**Additional context**

This is form a comment in the original PR. See  See https://github.com/microsoft/hlsl-specs/pull/59/files#r1234333788. We want a solution that is intuitive and easy to use, but does not lead to an ugly implementation. We will have to balance the two.

**Comment by cassiebeckley** [comment]
Fixed by #129.
