### ISSUE TITLE
Exclude TextureCubeArray from SampleCmpGrad support in upcoming orthogonal comparison sampling proposal

### ISSUE THREAD

**Issue by tex3d** [microsoft/hlsl-specs#81]
**Which proposal does this relate to?**
The not yet published orthogonal comparison sampling spec proposal.

**Describe the issue or outstanding question.**
Need to specify that `SampleCmpGrad` is not supported for the `TextureCubeArray` resource kind.

**Additional context**
Some current hardware does not support this combination.  It's excluded from the OpenGL spec, and though I do not see it excluded from SPIR-V, that may be an oversight, or the restriction may be stated somewhere I didn't see.

**Comment by pow2clk** [comment]
This was completed in #147
