### ISSUE TITLE
[0010] Define vk::BufferPointer pointee atomics

### ISSUE THREAD

**Issue by llvm-beanz** [microsoft/hlsl-specs#88]
**Which document does this relate to?**
[Proposal 0010 - vk::BufferPointer](https://github.com/microsoft/hlsl-specs/blob/main/proposals/0010-vk-buffer-ref.md)

**Describe the issue you see with the spec**
vk::BufferPointer::Get returns a reference. Can this reference be used with atomics?

**Additional context**
[See comment here](https://github.com/microsoft/hlsl-specs/issues/84#issuecomment-1708112403)

**Comment by devshgraphicsprogramming** [comment]
I think what me, @Ipotrick and @Dolkar are getting at is more along the lines, can the reference be used as an inline-spirv function argument declared with `[vk::ext_reference]`

I don't think the ability to just be able to pass the _immediate_ result of `Get` to `InterlockedAdd` and friends will make us happy.

**Comment by llvm-beanz** [comment]
@devshgraphicsprogramming, that's completely separate from what _this_ issue is tracking. The intent of _this issue_ is to track defining how `vk::BufferPointer` will interact with the current atomic operations. How it will interact with other Vulkan extensions is something we should track and discuss elsewhere.

I may have confused you by the comment that I linked to, but I think there are multiple issues here that need to be tracked and discussed separately.

**Comment by llvm-beanz** [comment]
@greg-lunarg, I'm going to put this one on my plate at least to start with. It relates to #89, and I have some questions I want to sort out relating to the address spacing of the references these APIs will return.

**Comment by devshgraphicsprogramming** [comment]
Can we make it the job of SPIR-V intrinsics (proposal 0011) to provide the atomics?
